### ISSUE TITLE
Error with HA 0.109.3

### ISSUE THREAD

**Issue by FireBall1725** [briis/smartweatherudp#10]
Upon upgrading to Home Assistant 0.109.3 the following error occurs when checking my configuration:

```Platform error sensor.smartweatherudp - cannot import name 'UNIT_UV_INDEX' from 'homeassistant.const' (/usr/src/homeassistant/homeassistant/const.py)```

**Comment by briis** [comment]
This has already been fixed. Please update to version 0.1.6

https://github.com/briis/smartweatherudp/releases/tag/V0.1.6
