### ISSUE TITLE
Typo in entity details

### ISSUE THREAD

**Issue by beaulebens** [briis/smartweatherudp#11]
<img width="378" alt="Screen Shot 2020-06-05 at 4 27 33 PM" src="https://user-images.githubusercontent.com/108942/83927223-81c76100-a749-11ea-8225-f5636745744c.png">

Noticed the small typo at the bottom of the entity details ("Smart Homer").

**Comment by beaulebens** [comment]
That string is found here: https://github.com/briis/smartweatherudp/blob/master/custom_components/smartweatherudp/sensor.py#L19

**Comment by LuckyJayTx** [comment]
Fixed this in v0.1.7
