### ISSUE TITLE
Requirements not found: ['pysmartweatherudp==0.1.7'].

### ISSUE THREAD

**Issue by schoenof** [briis/smartweatherudp#14]
Integration fails to load:

1st error:

Platform error: sensor - Requirements for smartweatherudp not found:['pysmartweatherudp==0.1.7'].

2nd error:

Unable to install package pysmartweatherudp==0.1.7: ERROR: Could not find a version that satisfies the requirement pysmartweatherudp==0.1.7 (from versions: 0.1.3, 0.1.4, 0.1.5, 0.1.6) ERROR: No matching distribution found for pysmartweatherudp==0.1.7 WARNING: You are using pip version 20.0.2; however, version 20.1.1 is available. You should consider upgrading via the '/usr/local/bin/python3 -m pip install --upgrade pip' command.

**Comment by briis** [comment]
Should be fixed now. The package is uploaded to pypi.

**Comment by schoenof** [comment]
fixed...works great...thx
