### ISSUE TITLE
"Rain Today" always 0

### ISSUE THREAD

**Issue by gdreves** [briis/smartweatherudp#18]
I installed yesterday and all other sensors are working as expected, but rain_today is always 0 despite the reading directly from the Tempest having a non-zero value

**Comment by LuckyJayDIY** [comment]
I have this fixed in the integration and will get an update published in the next day or two.

**Comment by gdreves** [comment]
Great to hear. Thanks!

**Comment by rmayron** [comment]
thanks for having a resolution.  Was the update released? (sorry, I'm a Github  newbie...)

**Comment by i00** [comment]
Any update? ... Lightning is the same

**Comment by wauswaus** [comment]
> 
> 
> I have this fixed in the integration and will get an update published in the next day or two.

Hi, any news on this update?

**Comment by macolinob** [comment]
Can we get this committed?

**Comment by gdreves** [comment]
@LuckyJayDIY are you able to commit the fix for this?

**Comment by i00** [comment]
Over 6 months after the fix and still no update?
