### ISSUE TITLE
Wind gust same as wind speed

### ISSUE THREAD

**Issue by Notrial** [briis/smartweatherudp#20]
Hi, 

I noticed that the wind guys value equals wind speed, so it's not reading proper values out of the unit.
Any chance you can look into that?

p.s. I have Tempest unit...would you recommend using your pySmartWeatherIO instead?

Thanks!

**Comment by scstraus** [comment]
I've opened a bit more detailed version of the same [here](https://github.com/briis/smartweatherudp/issues/27)

**Comment by wx-jc** [comment]
Can someone please fix this issue?  Wind gust and wind speed are showing the same value.
