### ISSUE TITLE
Warning in Startup Logs

### ISSUE THREAD

**Issue by jdc0730** [briis/smartweatherudp#24]
The following in being generated in the logs for this integration:

Logger: homeassistant.loader
Source: loader.py:802
First occurred: 5:39:20 PM (1 occurrences)
Last logged: 5:39:20 PM

No 'version' key in the manifest file for custom integration 'smartweatherudp'. This will not be allowed in a future version of Home Assistant. Please report this to the maintainer of 'smartweatherudp'

**Comment by natekspencer** [comment]
Fixed in release v0.1.8
