### ISSUE TITLE
Too much datapoints are slowing down performance

### ISSUE THREAD

**Issue by tom-x1** [briis/smartweatherudp#28]
Hey, thank you for this awesome integration, I have now issue with that it's more a feature request. I noticed that my WeatherUDP station is producing way too much datapoints. For every single sensor it sends several updates per second. Thats unnecessary for me as I (and probably most other users) don't need so much/exact data. It's also a problem regarding storage requirements. On one side you need more storage space and on the other side you need a more IO efficient storage to view a historical graph over the last 24h. I'm already using a SSD for my HA instance but it still takes about 5-7 seconds to load a single historical graph which looks back 24 hours. That data overload slows down all of my dashboards. 

So what would be nice would be the possibility to have and option to save just every X datapoint which is sent by the station. Personally I think for me it would be sufficient to keep only 10% of the data sent.

**Comment by ghgeiger** [comment]
I concur. Deleted my default SQLite DB 3 hours ago, & it's already up to 200 MB. I'll be purging the tempest data daily & keeping it in an influxDB for long term storage, but I'd love to be able to set the amount of time between logging datapoints. Once every 10 seconds, or even a minute or two would offer more than enough granularity for my needs. 

Thanks
