### ISSUE TITLE
Not working anymore on core-2021.6.2

### ISSUE THREAD

**Issue by BrianHollander-NL** [briis/smartweatherudp#29]
Under core-2021.6.2 i get this error on SmartweatherUDP, I already removed an reinstalled the integration
![image](https://user-images.githubusercontent.com/22517237/120855177-71c1a780-c57e-11eb-83a3-c7173c10e022.png)

**Comment by TheBassman** [comment]
I have the same issue after updating to core 2021.6.2. I had originally installed manually, and after the update broke the integration, I removed the custom_componants folder and installed via HACS. As soon as I add the platform to the configuration.yaml file, my configuration is no longer valid.

**Comment by marc-gist** [comment]
just add "version" key in the manifest.json file as per 
https://developers.home-assistant.io/blog/2021/01/29/custom-integration-changes/#versions

**Comment by theplaceilive** [comment]
I'm having the same issue on 2021.6.2 and added the version key to manifest.json with no success. 

What should the entry specifically look like? I've tried each of the following individually and each attempt continues to fail after a full system reboot. I used the existing manifest.json entries as examples for leading spaces and placement.  

"version": 
"version": "0.1.7"
"version": ["0.1.7"]

**Comment by marc-gist** [comment]
its JSON, your second one should work if you put a comma after the last item.

**Comment by theplaceilive** [comment]
Thanks for the clarification. I now realize I forgot to place a comma after the "requirements" key when adding "version": "0.1.7" as the last entry.

I've since corrected that and upgraded to core-2021.6.2.  Smart Weather UDP is now working fine.  Thanks again!

**Comment by natekspencer** [comment]
Resolved in release v0.1.8
