### ISSUE TITLE
Could not convert state to float

### ISSUE THREAD

**Issue by larstobi** [briis/smartweatherudp#3]
I have lots of this in my info tab under developer tools in Home Assistant:

`Could not convert <state sensor.smartweatherudp_wind_direction=SW; attribution=Powered by a Smart Homer Weather Station via UDP, last_update=2019-07-30 06:31:39, friendly_name=Wind Direction, icon=mdi:compass-outline @ 2019-07-30T08:31:40.010580+02:00> to float`

**Comment by natekspencer** [comment]
If this is still an issue after upgrading to v2021.12.0, please open a new issue.
