### ISSUE TITLE
entity weather.smartweather_tempest missing after update

### ISSUE THREAD

**Issue by Trukmeister** [briis/smartweatherudp#32]
A few updates back Weatherflow used to have an entity called weather.smartweather_tempest but I can no longer get that to show. Is it gone or am I missing something? I have the “weatherflow smart weather UDP sensor” installed in hacs which is where I think this entity came from but I cannot get the forecast from my Tempest. I have several lovelace items dependent on this entity which are dead. Any ideas or thoughts please and thanks!

**Comment by zacs** [comment]
@Trukmeister I believe the `weather.` entity came from the non-UDP integration here: https://github.com/briis/smartweather

**Comment by natekspencer** [comment]
I plan on adding a weather component to this in the next release.
