### ISSUE TITLE
Missing Version Number from Manifest.json file

### ISSUE THREAD

**Issue by paulforbing** [briis/smartweatherudp#34]
I have not had any luck setting this up with my Home Assistant. I am running 6.5 on the Home Assistant Blue hardware. I had to add this manually to the custom_components folder, as this repo is not showing as valid when adding it from the Add-On Store page. At the bottom is the line from my log file that indicates the "manifest.json" file being the problem. It is missing a version key and looks like it's been required now since April. 

More information from Home Assistant site. 
https://developers.home-assistant.io/blog/2021/01/29/custom-integration-changes/#versions 

This appears to be the new tool for validating new versions
https://developers.home-assistant.io/blog/2020/04/16/hassfest/

I have little experience in making/maintaining add-ons for something like this, so I'm not exactly sure what needs to be done here, I hope this information is sufficient. I am happy to provide additional data or test and relay results if that helps.

Thank you.

2021-10-29 09:11:23 ERROR (SyncWorker_0) [homeassistant.loader] The custom integration 'smartweatherudp' does not have a version key in the manifest file and was blocked from loading. See https://developers.home-assistant.io/blog/2021/01/29/custom-integration-changes#versions for more details

**Comment by natekspencer** [comment]
Resolved in v0.1.8
