### ISSUE TITLE
Failed to connect - host on other subnet

### ISSUE THREAD

**Issue by thrawnarn** [briis/smartweatherudp#42]
Since  v2021.12.0 I am unable to connect to my smartweather. I've tried to connect directly to the ip but it doesn't work, It worked flawlessly with the old version.
My smartweather is on another VLAN than HA, I've tried opening all ports but it doesn't work. Any ideas what to do?

**Comment by thrawnarn** [comment]
oops. I were wrong. I used the REST integration before, sorry.
But I would like to solve this problem. Any idea how to.

**Comment by natekspencer** [comment]
Truthfully, I have no personal experience with VLAN setups and UDP broadcasts. This article involving UDP broadcast forwarding may be of some use:

https://techhub.hpe.com/eginfolib/networking/docs/switches/WB/15-18/5998-8166_wb_2920_mrg/content/ch03s10.html#t_Example_of_a_UDP_packet-forwarding_environment

If it works, please let me know and I can add something to the README to help others that have a similar setup.
