### ISSUE TITLE
Wind Direction - rapid and average are combined

### ISSUE THREAD

**Issue by dubnom** [briis/smartweatherudp#48]
Tempest sends two different UDP packets that reference "Wind Direction" - the main observation packet and the rapid packet.  Even though these use the same field name ("Wind Direction"), I think the field means two different things.  I think the rapid packet is giving an immediate sample of wind speed and wind direction while the observation packet gives wind avg (over 3 seconds?) and wind direction (also over 3 seconds?)

**Comment by natekspencer** [comment]
This was resolved in 2022.7.0
