### ISSUE TITLE
Official Integration

### ISSUE THREAD

**Issue by jeeftor** [briis/smartweatherudp#51]
Any reason why you didn't go the official integration route with this?...

If ya'll don't mind I was thinking of taking your backing lib - and some of this code - and starting the official integration path ... VERY SLOW GOING to say the least of the process...

Which is perhaps why ya'll didn't move so fast. In any case - its not hard just takes months of mini changes etc ...

**Comment by natekspencer** [comment]
I think it's because custom integrations are easier to iterate on early in the process, which allows for a much quicker feedback loop.

I've been considering adding it to the official core repository as well, but just haven't gotten around to doing so yet. I've tried to keep this code in line with best practices from core, so it shouldn't be too big of a lift and shift. Fortunately this also only uses one of the domains (sensor), so it shouldn't take too long to get it all approved.

You're welcome to start the process and add me as a maintainer for it as well.

**Comment by jeeftor** [comment]
<img width="270" alt="image" src="https://user-images.githubusercontent.com/6491743/180076686-2c2e6dec-7233-4635-bb11-2d42e456ba84.png">

Already started ... 

Also I think we can do DHCP discovery based on hostname -> which I've done for my Intellifire Official integration...

And yes because its only Sensor it should be simpler... I'm pretty much going to just port your code over ... and then go through the wonderful PR process which ... I'm pretty sure adding Fan support for my fireplace module has been open for over a month! :)

**Comment by jeeftor** [comment]
Oh I forgot ... the Testing coverage is also really annoying - but luckily its really only the `config_flow` that needs coverage

**Comment by jeeftor** [comment]
Honestly it will probably take me some time to get all the testing implemented - but I've added you as a collaborator and I'll try to keep up with the changes ya'll make on this end...

**Comment by jeeftor** [comment]
This is actually a very nice integration as-is. 

I did rename it to `WeatherFlow` - which I hope is ok.

https://github.com/home-assistant/core/pull/75530

**Comment by natekspencer** [comment]
That sounds great! I would have renamed it as well. Also glad you put the domain name as just weatherflow. ^_^

**Comment by jeeftor** [comment]
Just working through the .pre-commit hooks ... for they are many! :) 

<img width="799" alt="image" src="https://user-images.githubusercontent.com/6491743/180088779-00afbb0a-169c-40f4-9bb0-e523a4646243.png">

**Comment by jeeftor** [comment]
<img width="722" alt="image" src="https://user-images.githubusercontent.com/6491743/180251550-5e6ae3ad-e03d-4dc6-9f61-4a52f509d920.png">

Well I'm closer on coverage but I'm really not sure how to mock out some of your async stuff...  regarding the `_async_has_devices` call ... I'll look into it more but Python Testing has been the bane of my understanding lately ... although I continue to get better..

If I get stuck I'll see if you are cool to pull down the branch I'm working on and give it a go ...

But if we have the coverage and they like the structure of how you developed everything we should be in a decent spot to get the PR accepted (also need docs which I can probably write up)

**Comment by jeeftor** [comment]
Also I think I can nix the `async_step_import` function because thats for YAML and if we go into the UI then we don't need YAML... does that jive with you?

**Comment by natekspencer** [comment]
> Also I think I can nix the `async_step_import` function because thats for YAML and if we go into the UI then we don't need YAML... does that jive with you?

Yeah, you should be able to delete anything associated with that yaml import as well as the deprecated sensors sections.

**Comment by jeeftor** [comment]
Will do!  

is the `in_progress` stuff related to YAML as well? I just opened the PR - and hopefully we'll get some comments ... you may want to add yourself to it for feedback:

https://github.com/home-assistant/core/pull/75530

**Comment by jeeftor** [comment]
So I looked at your backing lib which seems like it has a good suite of tests involved. I'm struggling to get coverage for this block.

<img width="556" alt="image" src="https://user-images.githubusercontent.com/6491743/180270270-e4514f04-1bbc-4829-afa4-b16649871075.png">

I'm assuming I (we) need to mock out the `WeatherFlowListener` - and fire off a fake `EVENT_DEVICE_DISCOVERED` ... Would you be down to take a crack - or point me in the right direction?

Think you'd be down to either point me in the right direction or just mock out something for that section? Otherwise I think stuff is mostly covered... 

(until the reviewers tear everything to shreds! :)

**Comment by jeeftor** [comment]
I'm thinking I have to mock out the entire `WeatherFlowListener` perhaps - and have the mock one emit an event somehow?
... does that sound correct?

**Comment by natekspencer** [comment]
If you take a look at https://github.com/briis/pyweatherflowudp/blob/main/test/test_client.py#L42 and the fixtures associated with it, you could replicate doing UDP broadcasts as the test. Otherwise, you could mock the WeatherFlowListener and send a "device_discovered" event.

**Comment by jeeftor** [comment]
I looks like your tests are actually opening/closing ports is that correct?

I tried to duplicate some of them

<img width="641" alt="image" src="https://user-images.githubusercontent.com/6491743/180312370-733a65d9-4ab4-429c-9d50-8104d1086e55.png">

and I'm getting: 
<img width="660" alt="image" src="https://user-images.githubusercontent.com/6491743/180312405-d3eedb08-7143-4622-beb7-1c8fdc86a005.png">

**Comment by jeeftor** [comment]
I think I'm running your tests in the HA environment...

**Comment by jeeftor** [comment]
So thinking this through -> you make a new `WeatherFlowListener` which calls the `__aenter__` function which then fires off the `startListenting` call:


```python
  async def start_listening(self) -> None:
        """Connect the UDP socket and start listening for messages."""
        if self._udp_task is not None:
            return

        try:
            self._udp_connection = await open_local_endpoint(
                host=self._host, port=self._port
            )
        except OSError as ex:
            if "Address already in use" in ex.args:
                raise AddressInUseError("Address already in use") from ex
            raise EndpointError("Could not open a local UDP endpoint") from ex
        _LOGGER.debug("Started listening")
        self._udp_task = asyncio.ensure_future(self._start_socketreader())
```

So I want to replace that call with "something" that will "inject" a `udp_task` that reports out on the device status using the details in `device_status.json`....

That way I don't hit the network and I "should" be able to keep the rest of the logic...

**Comment by jeeftor** [comment]
And looking closer I'll want to emit this event:


```python
self.emit(EVENT_DEVICE_DISCOVERED, "HB-00000001")
```

So if I can turn off network access AND emit this device I can probably get the coverage moving forward :)

**Comment by jeeftor** [comment]
Thanks for the help -> I'm getting much closer

**Comment by jeeftor** [comment]
Only line now that is failing is 102 which is the block:

```python
        # Cancel other flows.
        for flow in in_progress:
            self.hass.config_entries.flow.async_abort(flow["flow_id"])
```

I'm assuming this is an artifact of something being declared twice in YAML? I'm assuming i can probably remove it - but wanted to check - although I might just remove it anyways and you can tell me to put it back in.

**Comment by natekspencer** [comment]
It should be fine to remove. We may need to add something back in if we add discovery. But that should be ok

**Comment by jeeftor** [comment]
I believe there is 100% test coverage + documentation + 2PRs open ... so now we wait :)

**Comment by jeeftor** [comment]
I got dinged here:

<img width="281" alt="image" src="https://user-images.githubusercontent.com/6491743/180482682-8de89b3c-a86c-4be1-85a7-816bbe368aa7.png">

Seems the runner kills tests that hang for 9 seconds... and I was trying to hang for 10 to get the timeout error... 🤣

**Comment by jeeftor** [comment]
I assume I can patch `event.wait()` to throw a timeout error which would probably solve the problem.

**Comment by natekspencer** [comment]
Use `from tests.common import async_fire_time_changed` to mock things like sleep or wait

**Comment by natekspencer** [comment]
Also, if you'd change the sensor name for `Wind Average` to `Wind Speed Average` just so it is more clear. I hadn't done it in this project because I didn't wanna break anything. But since it is changing, might as well make that change anyway haha

**Comment by jeeftor** [comment]
<img width="373" alt="image" src="https://user-images.githubusercontent.com/6491743/180486922-d25ede38-76e7-4925-be01-99af2dc7cbdd.png">

Yea that makes much more sense :)

**Comment by jeeftor** [comment]
I know they posted new naming standards for "things" in the last release - but I'm assuming this is in compliance with them ... 

I think it was <room>.<entity><device> or something

**Comment by natekspencer** [comment]
> <img alt="image" width="373" src="https://user-images.githubusercontent.com/6491743/180486922-d25ede38-76e7-4925-be01-99af2dc7cbdd.png">
> 
> Yea that makes much more sense :)

key still needs to be "wind_average" since that is the name in the library

**Comment by natekspencer** [comment]
> I know they posted new naming standards for "things" in the last release - but I'm assuming this is in compliance with them

It looks like we'll need to change things to starting with a capital letter, and then lowercase everything else. So this would be "Wind speed average"
https://developers.home-assistant.io/blog/2022/07/10/entity_naming

**Comment by jeeftor** [comment]
Updated ...

Just need to tweak that timing out test better... thought I had it working
... but at least i figured out how to make my local python operate the same
regarding the timeout interval

**Comment by jeeftor** [comment]
Keeping this alive. Waiting on mods to look it over

**Comment by HyperActiveJ** [comment]
I am also interested. Please let me know if there's anything I can do. Are you just waiting for a reviewers on the pull request?

**Comment by jeeftor** [comment]
Just waiting on reviewers to have a look.
