### ISSUE TITLE
Rain Accumulation Today?

### ISSUE THREAD

**Issue by beaulebens** [briis/smartweatherudp#52]
I'm using this integration with a Tempest weather station, and I'm interested in seeing the amount of rain accumulation.

I see there is this sensor created; 

https://github.com/briis/smartweatherudp/blob/17972ca326a43eb01a95ec139d5c29ab95044996/custom_components/smartweatherudp/sensor.py#L230-L238

But I don't see anything that would match up with the "Local Day Rain Accumulation" (index 11, documented https://weatherflow.github.io/Tempest/api/udp/v171/). 

Would it be possible to add this sensor?

**Comment by natekspencer** [comment]
Unfortunately that field is only on the sky system and not the tempest. And from my understanding, it actually doesn't even get populated for those either (always comes back as 0 or null). With that being said, rain accumulation data is available in Home Assistant via the long term statistics. But to display a graph to show the accumulation by day, you need to use a custom card like apex charts.

**Comment by beaulebens** [comment]
Ah I didn't realize they were different systems. OK, thanks. I'll see if I can set something up using long term stats, that resets daily.
