### ISSUE TITLE
Need to reload integration after Home Assistant restart

### ISSUE THREAD

**Issue by patdemko** [briis/smartweatherudp#56]
I'm not sure when this started happening (it's possible it was the February or March HA release), but now after every time my home assistant restarts I have to reload this integration to get it start picking up my weather data again.  As soon as I reload the integration, it starts updating the data again.  I've held off on reporting it since it's not that hard to just reload the integration, but since it's been a while and it's still happening I thought I'd report it. Not sure if there's any other information or logs that could help you figure this out.  Thanks!

**Comment by natekspencer** [comment]
You'll want to uninstall and remove this integration and then use the core integration now.

**Comment by patdemko** [comment]
Thanks!  That did it.
